language: android
jdk: oraclejdk8
sudo: false
os: linux
    
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    
    # Emulator settings
    - sys-img-armeabi-v7a-android-28

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'android-sdk-preview-license-.+'
  
script:
   - ./gradlew runUnitTests
