language: android
jdk: oraclejdk8
sudo: false
os: linux
    
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
    
    # Emulator settings
    - sys-img-armeabi-v7a-android-28

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'android-sdk-preview-license-.+'
  
before_script:
  - echo y | android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | android update sdk --no-ui --all --filter extra-android-support
  - echo y | android update sdk --no-ui --all --filter "android-28"
  - echo y | android update sdk --no-ui --all --filter build-tools-28.0.3
  - echo y | android update sdk --no-ui --all --filter "sys-img-armeabi-v7a-android-28"
  - echo no | android create avd --force -n test -t "android-28" --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  
script:
  - android-wait-for-emulator
  - adb shell input keyevent 82
  - adb shell svc power stayon true
  - ./gradlew connectedCheck --info -PdisablePreDex;
